** Aesthetics - The Look and Feel.

Having configured Magit and Helm, Emacs has now got the bare minimum
that I would like to have in place to make the software work. But of
course, there are lots of things that will need to be done to make it
as good as I know it can be.

For now the configuration is addressing just the look and feel of
Emacs. It isn't particularly ugly, but it is staid in its appearance,
and there is screen furniture that I would like to get rid of because
it is stuff that I don't really need or want.

*** Minimise the Screen Furniture in the Emacs Window.

Keep the Emacs window as clean as possible by switching off the stuff
that isn't needed, which is almost everything.

#+begin_src emacs-lisp
  ;; Switch off unnecessary screen furniture.
  (menu-bar-mode 0)			; No menu bar
  (tool-bar-mode 0)			; No tool icon bar
  (blink-cursor-mode 0)			; Steady, non-blinking cursor
  (scroll-bar-mode 0)			; Hide the scroll bar
  (display-battery-mode 1)		; Battery info in the mode line
#+end_src 

*** Turn Off the Splash Screen.

This doesn't really have any impact when I am using Emacs client as
the splash screen isn't shown in Emacs client mode. Turning it off
anyway for those rare occasions where I do use the normal Emacs. I'll
modify the text displayed in the next section.

#+begin_src emacs-lisp
  ;; Switch off the splash screen.
  (setq inhibit-startup-message t)
#+end_src

*** Change Scratch Buffer Text Display.

#+begin_src emacs-lisp
  ;; Display pithy text based on the system name.
  (if (string=(system-name) "ziggyi5")
      (setq initial-scratch-message
  	  "\n\n\n\t\tWelcome to the Church of Emacs..."))
  (if (string=(system-name) "uk-rfieldse-l")
      (setq initial-scratch-message
  	  "\n\n\n\tEverything's science-fiction until someone makes it science fact.\n\n\t\tMarie Lu"))
#+end_src
