** Aesthetics - The Look and Feel.

Having configured Magit and Helm, Emacs has now got the bare minimum
that I would like to have in place to make the software work. But of
course, there are lots of things that will need to be done to make it
as good as I know it can be.

For now the configuration is addressing just the look and feel of
Emacs. It isn't particularly ugly, but it is staid in its appearance,
and there is screen furniture that I would like to get rid of because
it is stuff that I don't really need or want.

*** Minimise the Screen Furniture in the Emacs Window.

Keep the Emacs window as clean as possible by switching off the stuff
that isn't needed, which is almost everything.

#+begin_src emacs-lisp
  ;; Switch off unnecessary screen furniture.
  (menu-bar-mode 0)			; No menu bar
  (tool-bar-mode 0)			; No tool icon bar
  (blink-cursor-mode 0)			; Steady, non-blinking cursor
  (scroll-bar-mode 0)			; Hide the scroll bar
  (display-battery-mode 1)		; Battery info in the mode line
#+end_src 

*** Turn Off the Splash Screen.

This doesn't really have any impact when I am using Emacs client as
the splash screen isn't shown in Emacs client mode. Turning it off
anyway for those rare occasions where I do use the normal Emacs. I'll
modify the text displayed in the next section.

#+begin_src emacs-lisp
  ;; Switch off the splash screen.
  (setq inhibit-startup-message t)
#+end_src

*** Change Scratch Buffer Text Display.

#+begin_src emacs-lisp
  ;; Display pithy text based on the system name.
  (if (string=(system-name) "ziggyi5")
      (setq initial-scratch-message
  	  "\n\n\n\t\tWelcome to the Church of Emacs..."))
  (if (string=(system-name) "uk-rfieldse-l")
      (setq initial-scratch-message
  	  "\n\n\n\tEverything's science-fiction until someone makes it science fact.\n\n\t\tMarie Lu"))
#+end_src

*** Turn On a Suitable Dark Mode.

#+begin_src emacs-lisp
  ;; badwolf theme (for the time being)
  (load-theme 'badwolf t)
#+end_src

To make the themes work use 'package-install' and install the theme
first, then use the above to activate the required theme. I have also
installed dracula so I can switch back and forth without any further
action. I use badwolf in Vim as well, so it may be nice to have visual
similarity, but also need to consider which colour scheme is nicer
going forward.

*** Set a Nice Font.

I got into a bit of a broken state, so ended up winding back to the
previous commit!

A nice, easy to read font is a must when you consider the look and
feel of a text editor. Hack is a popular choice, and I'm currently
settling on size 12, but I may make it a bit smaller going forward.

The text is easy to read and nice and friendly, so I won't investigate
any alternatives for the time being.

#+begin_src emacs-lisp
  ;; Set the font to hack
  (add-to-list 'default-frame-alist '(font . "Hack-12"))
  (set-face-attribute 'default nil
  		    :family "Hack")
#+end_src

*** A Better Frame Heading.

The default Emacs frame heading is along the lines of:

<filename> - GNU Emacs at <System Name>

This isn't bad, but I don't think I really need the system name on
display, and it would be useful to identify the filename and buffer
name in case these are different.

#+begin_src emacs-lisp
  ;; Modifying the frame title shown for the Emacs window.
  (setq frame-title-format '("Emacs - Buffer: %b > File: %f"))
#+end_src

With the above stanza in effect the full frame title now reads:

Emacs - Buffer: aesthetics.org > File: /home/rjf/zconfig/emacs/
.emacs.d/aesthetics.org

*** Highlighting The Current Line.

With a larger font size and what looks a good colour theme, I'm not
sure how necessary this setting is going to prove to be, but I am
adding it because it can make it easier to find your cursor in a sea
of text.

#+begin_src emacs-lisp
  ;; Turn on the highlighting for the current line.
  (global-hl-line-mode 1)
#+end_src

The highlighting is subtle, but worth keeping. It is almost invisible
when you are working on the specific line and adding code, but move
the cursor to an existing line and the highlighting is much more
obvious. I guess that this is a good implementation because it makes
it easier to find the cursor when you have moved away from the working
point but doesn't overload the view when you are actually typing.

*** Replace the Standard Modeline with the Doom Emacs Version.

The standard modeline isn't bad. It contains useful information such
as the file name, active mode and your location within the file (as
I'm writing this I am at the bottom of the file, which happens to be
line 128 and I'm working on the 'Emacs' branch of the repository.

However, the modeline isn't pretty, so I have previously swapped out
the standard one for the Doom Emacs version. It is just a bit more
'eye candy'.

#+begin_src emacs-lisp
  ;; Activate the Doom Emacs Mood Line.
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))
#+end_src

The Doom Emacs modeline includes an icon to display the file type at
the left hand side. If this doesn't show the icon then follow the
instructions below. By 'properly', the usual behaviour is to show a
Unicode character which is displayed as a square with squiggles inside
it.

To install the icons use the command:

M-x nerd-icons-install-fonts

This will download and install the font and run the font update
command.

*** Making the Emacs Window Transparent.

The definition of aesthetic configuration options is this one. It
serves no real practical function, but it does make for the sort of
eye-candy that I love.

The stanza activates the transparency and configures two different
levels of opacity. If the Emacs window is active then the opacity is
80%, but if another program is active on the screen then the opacity
is just 50%.

As with many of the settings, these can be tweaked for greater or
lesser transparency.

In order to work, a compositor needs to be available and running. In
the case of my i3wm login this is managed by compton. The
configuration file for this is stored in the i3wm configuration
folder, and I haven't made any modifications to this that I recall.

#+begin_src emacs-lisp
  ;; Transparency. The ultimate in eye-candy goodness.
  (set-frame-parameter (selected-frame) 'alpha '(80 50))
  (add-to-list 'default-frame-alist '(alpha 80 50))
#+end_src

Testing these settings, the transparency works as expected with the
bad wolf theme. The background image is visible, but so is the
text. Just what I like.

*** Fancy Bullets for Org Mode.

The configuration files that I'm using to customise Emacs use the
Emacs 'Org Mode'. Org Mode is a form of MarkDown, which, like other
MarkDown dialects use a range of simple normal characters to identify
the structure and layout of the file. This can be used as a way of
creating relatively straightforward documents quickly and easily.

In the Org Mode Markdown the headings of the document are identified
by one or more asterisks at the beginning of the line. One asterisk is
a level 1 heading (equivalent to h1 in html or \section in LaTeX).

The asterisks are easy to use, but Emacs also supports a prettier icon
for each heading level which is automatically shown on the basis of
the number of asterisks used.

#+begin_src emacs-lisp
  ;; Pretty bullets for Org Mode markdown.
  (use-package org-bullets
    :config (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+end_src

Once this package is installed and operating then level 2 heading is a
circle and level 3 is a starburst star. Pretty!

A short comment on the Org file structure. The use of the
headings/section identifiers has a useful additional feature. As the
document gets longer and has the multiple sections then you can use a
simple 'folding' function to hide the contents of the various sections
of the file, seeing just the section headings. It works like this:

- Navigate to the beginning of the Org file where there is a heading

- Hit 'Tab' to fold all the sections. You'll just see the heading. Any
  other headings at the same level will also be displayed.

- Hit 'Tab' again and the sub-headings and the contents under the top
  level will be displayed. Using 'Tab' allows you to cycle through the
  visibility of the various sections.

It takes a little bit of getting used to, but it is a great way of
seeing the document structure.

*** Emacs Fire - I'll Teach You To Burn.

In the write-up for transparency I mentioned that that was probably
the biggest purely aesthetic plug-in for Emacs, but, in hindsight the
Emacs fireplace has it beat!

Start the fireplace using the command:

M-x fireplace

The fire can be controlled using:

C-+ - Move fire up
C-- - Move fire down
C-* - Toggle smoke on and off
q   - Quit the fireplace

#+begin_src emacs-lisp
  ;; Fireplace you can't cook marshmallows on.
  (use-package fireplace)
#+end_src

*** IBM Selectric Mode.

The rest of this file has been about the aesthetics of the Emacs
display. This isn't aesthetics, but it also isn't a useful function,
it is the auditory equivalent of aesthetics. The function, when
activated, makes Emacs keystrokes make the same iconic sound as a
classic IBM Selectric typewriter.

#+begin_src emacs-lisp
  ;; Selectrics Mode
  (use-package selectric-mode)
  (require 'selectric-mode)
#+end_src

