** Aesthetics - The Look and Feel.

Having configured Magit and Helm, Emacs has now got the bare minimum
that I would like to have in place to make the software work. But of
course, there are lots of things that will need to be done to make it
as good as I know it can be.

For now the configuration is addressing just the look and feel of
Emacs. It isn't particularly ugly, but it is staid in its appearance,
and there is screen furniture that I would like to get rid of because
it is stuff that I don't really need or want.

*** Minimise the Screen Furniture in the Emacs Window.

Keep the Emacs window as clean as possible by switching off the stuff
that isn't needed, which is almost everything.

#+begin_src emacs-lisp
  ;; Switch off unnecessary screen furniture.
  (menu-bar-mode 0)			; No menu bar
  (tool-bar-mode 0)			; No tool icon bar
  (blink-cursor-mode 0)			; Steady, non-blinking cursor
  (scroll-bar-mode 0)			; Hide the scroll bar
  (display-battery-mode 1)		; Battery info in the mode line
#+end_src 

*** Turn Off the Splash Screen.

This doesn't really have any impact when I am using Emacs client as
the splash screen isn't shown in Emacs client mode. Turning it off
anyway for those rare occasions where I do use the normal Emacs. I'll
modify the text displayed in the next section.

#+begin_src emacs-lisp
  ;; Switch off the splash screen.
  (setq inhibit-startup-message t)
#+end_src

*** Change Scratch Buffer Text Display.

#+begin_src emacs-lisp
  ;; Display pithy text based on the system name.
  (if (string=(system-name) "ziggyi5")
      (setq initial-scratch-message
  	  "\n\n\n\t\tWelcome to the Church of Emacs..."))
  (if (string=(system-name) "uk-rfieldse-l")
      (setq initial-scratch-message
  	  "\n\n\n\tEverything's science-fiction until someone makes it science fact.\n\n\t\tMarie Lu"))
#+end_src

*** Turn On a Suitable Dark Mode.

#+begin_src emacs-lisp
  ;; badwolf theme (for the time being)
  (load-theme 'badwolf t)
#+end_src

To make the themes work use 'package-install' and install the theme
first, then use the above to activate the required theme. I have also
installed dracula so I can switch back and forth without any further
action. I use badwolf in Vim as well, so it may be nice to have visual
similarity, but also need to consider which colour scheme is nicer
going forward.

*** Set a Nice Font.

I got into a bit of a broken state, so ended up winding back to the
previous commit!

A nice, easy to read font is a must when you consider the look and
feel of a text editor. Hack is a popular choice, and I'm currently
settling on size 12, but I may make it a bit smaller going forward.

The text is easy to read and nice and friendly, so I won't investigate
any alternatives for the time being.

#+begin_src emacs-lisp
  ;; Set the font to hack
  (add-to-list 'default-frame-alist '(font . "Hack-12"))
  (set-face-attribute 'default nil
  		    :family "Hack")
#+end_src

*** A Better Frame Heading.

The default Emacs frame heading is along the lines of:

<filename> - GNU Emacs at <System Name>

This isn't bad, but I don't think I really need the system name on
display, and it would be useful to identify the filename and buffer
name in case these are different.

#+begin_src emacs-lisp
  ;; Modifying the frame title shown for the Emacs window.
  (setq frame-title-format '("Emacs - Buffer: %b > File: %f"))
#+end_src

With the above stanza in effect the full frame title now reads:

Emacs - Buffer: aesthetics.org > File: /home/rjf/zconfig/emacs/
.emacs.d/aesthetics.org

*** Highlighting The Current Line.

With a larger font size and what looks a good colour theme, I'm not
sure how necessary this setting is going to prove to be, but I am
adding it because it can make it easier to find your cursor in a sea
of text.

#+begin_src emacs-lisp
  ;; Turn on the highlighting for the current line.
  (global-hl-line-mode 1)
#+end_src

The highlighting is subtle, but worth keeping. It is almost invisible
when you are working on the specific line and adding code, but move
the cursor to an existing line and the highlighting is much more
obvious. I guess that this is a good implementation because it makes
it easier to find the cursor when you have moved away from the working
point but doesn't overload the view when you are actually typing.
