** Markup Language Editing Modes.

When writing text in Emacs, you aren't given access to things like
headers, fonts and justification types.  Emacs is just a place to
write your text into a file.

But there is always going to be a need to have the text you type into
Emacs turned into an attractive document.  This can be achieved by
using one of the available markup languages.  If you are writing for
the World Wide Web, for instance, then you might choose to write your
document using HTML and CSS. This is made more straightforward within
Emacs by using the Emmet mode.  Alternatively, if you are printing a
longer document which involves internal cross-referencing, insertion
of citations, bibliographies and an index then LaTeX is a good choice
to create the document in, and the Emacs mode AucTeX will help you
achieve complex documents easily.  This document itself is largely
written in a markup language. It uses a dialect of Markdown, and
documents like it can be turned into attractive documents by using a
suitable processing pipeline.  I haven't really investigated this
approach because I like using LaTeX so much.

So this configuration file will be targeted at adding the various
configurations to make these markup languages work.

*** Groff/Troff Editing.

A stalwart of the document creation software has been the roff
programs.  Standing for 'run-off', these are tools for making
relatively simple documents, though they do have a range of macros
available that can be used to enhance the functionality.

Originally there were two programs, troff and nroff. nroff is the
processor that creates documents suitable for tty systems which assume
a standard character width and limited enhanced formatting. troff
defaults to writing out Postscript documents which are suitable for
use with laser printers, but which are more likely to be used in
modern systems to generate a PDF document (PDFs are, at their heart, a
wrapper around a Postscript file).

Emacs has an nroff mode which is activated when a file with the
extension .ms is opened. There is an nroff-electric-mode which helps
creating the document by generating the second half of a tag when they
come in pairs. An example for this is the command to centre some
text. Centring is started using .(c on its own at the start of a
line. The following line is formatted as centred, and then the start
of the line when the centring stop is .)c on its own. If
nroff-electric is activated then C-j will carry out an electric
return, inserting the closing tag. The nroff mode doesn't need to be
activated, but the electric mode can be configured to be activated
when the nroff mode hook is encountered.

#+begin_src emacs-lisp
  ;; activate nroff electric mode when nroff mode is activated.
  (add-hook 'nroff-mode-hook 'nroff-electric-mode)
#+end_src

Testing shows that this works, and that opening an nroff file
activates both nroff mode and the nroff electric mode.

A couple of useful links for learning about Groff are:

https://opensource.com/article/18/2/writing-academic-papers-groff-me

This is especially useful, including instructions on creating a title
page, and the Groff equivalent of smart quotation marks.

https://douglasrumbaugh.com/post/groff-introduction/

Less advanced, but still useful, especially regarding the processor
pipeline for turning the Groff files into a PDF file.

https://www.gnu.org/software/emacs/manual/html_node/emacs/Nroff-Mode.html

The very short page on nroff mode in Emacs.

Finally, there are a couple of books that I have. One is in my Dropbox
eBook folders and is called 'Unix Text Processing'. It covers
nroff/troff as well as some very low level text editing tools (ed)! It
is the sort of publication that considers using Awk a method of
editing your documents... I also have a physical book which is the
partner book of the above, covering the macros for things like
inserting graphics and equations.

In summary, the Groff system is a workable method of creating
documents, and is somewhat lower weight than LaTeX, but the source
files are somewhat more difficult to read, being sparse in the
extreme. It is interesting to use, but it isn't something I would
want to rely on, especially when, over in the LaTeX camp the tools for
writing your documents include AucTeX for document creation and
latexmk for being able to work with a simple, largely automated
workflow.

*** HTML and CSS Editing Using Emmet Mode.

HTML wasn't the first markup language that I learned when using Linux,
that was LaTeX when I was trying to deal with the lack of a good word
processor, but HTML came along pretty soon after, and is probably the
one that I have spent the most time using in a work environment. The
tooling for writing HTML and CSS was very basic in the early days, but
when the more formalised structures of XHTML and HTML5 came along the
tooling for the document creation improved, aided by the improved
structural rigour required by the documents. It is still possible to
write your documents well, by hand, but when there is Emmet, why would
you?

Emmet helps building HTML documents quickly by inserting a structured
set of tags and then expanding them into a structured set of tags that
can then have the relevant text added to complete the page. The best
example is getting started in a HTML file. Open a fresh, empty
document with the html file extension, and then type html5 at the top
of the file, and with the cursor immediately after the 5 hit
'C-j'. The text is replaced with a simple, but valid HTML
skeleton. Further sections are either added by hand, or by adding
further tags and expanding those as required.

There are a number of cheatsheets to help users work out the
expandable tags for use with Emmet, but as you get used to it the
process gets better, and soon you will be adding an unsorted list with
seven list items, each of which is a link to another file...

The github page for Emmet mode includes useful abbreviations:

https://github.com/smihica/emmet-mode?tab=readme-ov-file

#+begin_src emacs-lisp
  ;; Emmet mode - activation and further configuration
  (use-package emmet-mode)
  (require 'emmet-mode)
  (add-hook 'sgml-mode-hook 'emmet-mode)
  (add-hook 'css-mode-hook 'emmet-mode)
  (setq emmet-move-cursor-between-quotes t) ; place cursor between quotes
#+end_src

The above is very much the same as the Emmet configuration that I have
used previously apart from using the sgml mode hook to activate Emmet
mode, rather than HTML mode, and the last line which places the cursor
between the first set of speech marks when a tag is expanded.

To understand why this is a benefit, consider the tag expansion to
insert a link to a stylesheet. To add the link navigate to either the
line above or below the title tag and, on a line on its own insert:

link

With the cursor at the end of the word press C-j. Emmet will expand
this to the following:

<link href="" rel="stylesheet"/>

With the function in place to move the cursor to the speechmarks, the
file name for the stylesheet can be added without further ado.

*** LaTeX Editing Using AucTeX Mode.

Back when I first installed Linux in the late 1990s, I purchased a
copy of a word processor because this was before you could do these
sorts of things online using Google Docs or M365. Worth highlighting
that I didn't have access even to dial-up internet at this
point. Unfortunately the word processor was not a mature product, and
without investing in paid for fonts, the fonts provided were pretty
fugly (and that is before discovering that the application was pretty
unstable)!

As this was the case, I began to look for an alternative, and while
reading the O'Reilly 'Learning Emacs' book I found out about LaTeX. I
purchased a book about the LaTeX system, and began the long journey of
learning how to write documents in the LaTeX markup language.

LaTeX is a complex markup language, and crafting it by hand would be a
major chore. Fortunately AucTeX makes it much simpler.

#+begin_src emacs-lisp
  ;; Install AucTeX to support LaTeX editing.
  (use-package auctex
    :defer t
    :ensure t)
  ;; Add RefTeX for Reference and Link Management
  (require 'reftex)
  (setq reftex-plug-into-AUCTeX t)
  ;; Switch on auto-saving for LaTeX documents
  (setq TeX-auto-save t)
  ;; Switch on Electric mode for AucTeX
  (setq TeX-electric-escape t)
  ;; Make AucTeX parse documents for included documents and the like.
  (setq TeX-parse-self t)
  ;; Set the master document to nothing by default.
  (setq-default TeX-master nil)
  ;; Turn on RefTeX for both native LaTeX and latex modes.
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex)
  (add-hook 'latex-mode-hook 'turn-on-reftex)
  ;; Activate the Flyspell mode
  (add-hook 'latex-mode-hook 'flyspell-mode)
  (add-hook 'LaTeX-mode-hook 'flyspell-mode)
  ;; Math Mode On
  (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
  (add-hook 'latex-math-mode 'LaTeX-math-mode)
  ;; Activate Outline Minor Mode
  (add-hook 'LaTeX-mode-hook 'outline-minor-mode)
  (add-hook 'latex-mode-hook 'outline-minor-mode)
  ;; Folding enabled for macros and environments.
  (add-hook 'latex-mode-hook (lambda ()
  			     (TeX-fold-mode 1)))
  (add-hook 'LaTeX-mode-hook (lambda ()
  			     (TeX-fold-mode 1)))
  ;; Set me as the default author.
  (setq LaTeX-default-author '("Richard Fieldsend"))
#+end_src

When writing documents using LaTeX there are two ways of being able to
see what your document will eventually look like. The simplest one is
to save the file and then use 'C-c C-c'. This will process the LaTeX
file and generate the viewable pages. It may be necessary to use the
C-c C-c several times if the document is getting complex as it may
need to call latex and bibtex and then latex again. After the required
processes have been run then the option changes to 'View' and the
output file will be opened and displayed.

The second approach is to use the latexmk package which runs like a
specialised version of make, processing the files using the relevant
packages until a final product is created. The advantage of latexmk is
that it can be used in a continuous mode which will update whenever
the latex file is saved.

latexmk -pvc -pdf <filename.tex>

The only issue to be aware of is that you should try and save the
LaTeX file when it is internally consistent and will compile without
errors. If this isn't the case then the latexmk output will show that
compilation has errored and it will need to be prodded back into life.

Initially the pdf file was always opened in xdvi rather than evince,
but this has been resolved by creating a .latexmkrc file in the root
of my home folder as outlined on this page:

https://mgeier.github.io/latexmk.html

This fixes the issue, triggering the pdf to be opened in evince, which
has the bonus that it updates whenever the pdf file is updated.

*** BibTeX and eBib - Bibliographic Support for LaTeX Documents.

The reality is that I don't really need to have bibliographic
functionality as part of my LaTeX system as I'm not writing anything
like an academic paper, but I like the idea of using Emacs as a
bibliographic database for storing the physical books I have on
shelves throughout the house, and eBooks that I have on my Kindle or
computer.

This will initially be a placeholder and I'll come back to this when I
have read through some of the finer points of BibTeX such as the
dialect to use, and the differences between them.

*** Org Mode Code Entangling - Indentation of Code.

The configuration I am creating for my Emacs setup uses the Emacs
Org-Mode markdown which is a dialect of Markdown, but with a very
special capability.  This is usually referred to as code tangling.
The Org files can have code segments embedded in the body of the
document.  In the case of the Emacs configuration, these embedded code
segments use Emacs Lisp in code wrapped in a begin source and end
source tag.  It is possible, however, to use Org Mode to embed these
sections and use a number of different languages, including Python, C
and R.  It becomes possible, therefore, to use Org Mode in a similar
way to Jupyter in Emacs, creating documents with usable code segments
embedded in them.  I don't use this outside of configuring Emacs, but
it may be something to look into in the future.

The concept provides support for the paradigm 'Literate Programming'
described by Donald Knuth, famed, also, as being the creator of
LaTeX. The concept sees you writing your document as prose which
describes what the program does, and any appropriate information about
things like the algorithm used, and then, at the appropriate place,
the code itself can be embedded in the prose. It can then be executed
by placing a cursor in the code segment and calling for the code to
run.  I think of this as being the logical extension of the concept of
the program comment, with the balance between the comments and the
code being flipped around.

This section addresses an issue that has arisen in the past with the
code sections. The indentation of the code within the code section can
be problematic in the case of languages where indentation is part of
the program language structure (most obviously Python). The code
stanza ensures that the variable that manages the functionality of the
tab key is set to true.

#+begin_src emacs-lisp
  ;; Indent the content of code blocks appropriately
  (setq org-src-tab-acts-natively t)
#+end_src

As noted in a previous iteration of the Emacs configuration, checking
the value of this variable, it is already to the t (true). I'll leave
the code in place anyway.
