** Programming Support Modes.

I hope it is obvious that one of the major activities for which
computers are used is programming. Emacs is eminently suited for these
activities, especially when the appropriate plug-ins and support
packages are added in.

From managing the compilation process of C/C++ programs using
Makefiles, to having Clojure/Lisp supporting Paredit functions which
allow items to be slurped into or barfed out of brackets, there are
lots of tools to make the process easier and less error prone.

*** Makefile Mode.

When programming in C/C++, the compilation process is managed using a
makefile stored in the same folder as the source files. The file is
named 'Makefile' by convention. The structure for the command for a
single source file to be compiled is something like:

name:
     compilation command

The compilation command will be of the form:

gcc -Wall source_name.c -o binary_name

the -Wall flag will run the appropriate warnings for any issues with
the code or in the compilation process.

The equivalent for compiling a C++ code base would be:

g++ -Wall source_name.cpp -o binary

In each case, calling the compilation process within Emacs is a matter
of using:

M-x compile

This will ask for the command:

make -k

add the name part of the Makefile entry to the end of the command and
the compilation command will be run.

The compilation process output is displayed in a second
buffer. The compiled binary can be run using 'eshell' (a bash style
shell running within an Emacs buffer) or from a terminal.

Recompilation reflecting changes in the source code can be done by
using the -B switch. To do this, add the flag before the -Wall flag:

gcc -B -Wall sourcefile.c -o binaryfile

*** Lisp and Clojure Programming.

Lisp programming is inherent to the Emacs system because most of the
macros that are used are written in the language (though the core
engine is written in C).

**** Paredit Mode for Lisp Programming.

Lisp structure is very dependent on the use of brackets (primarily the
parenthesis type). There are already functions in place to help with
the use of parentheses in the writing of text, such as the closing
half of the pair being added automatically, highlighting of the
matching halves of a pair when the cursor is on the opening character,
or immediately after the closing one and the rainbow colouring of the
brackets to help with understanding and checking the balance of these
pairs.

Paredit is another set of functions which help support the use of
brackets within coding.

#+begin_src emacs-lisp
  ;; Load Paredit for Lisp files.
  (use-package paredit)
  (autoload 'enable-paredit-mode "paredit" "Turn on pseudo-structural editing of Lisp code." t)
  (add-hook 'emacs-lisp-mode-hook #'enable-paredit-mode)
  (add-hook 'eval-expression-minibuffer-setup-hook #'enable-paredit-mode)
  (add-hook 'ielm-mode-hook #'enable-paredit-mode)
  (add-hook 'lisp-mode-hook #'enable-paredit-mode)
  (add-hook 'lisp-interaction-mode-hook #'enable-paredit-mode)
  (add-hook 'clojure-mode-hook #'enable-paredit-mode)
#+end_src

Parameters can be pulled into bracket pairs using 'slurp' and ejected
using 'barf'. There are other functions provided by the paredit
function. Examples of these behaviours are described on this page:

https://sansarip.github.io/owlbear/paredit.html

The functions provided are bracket aware, so can be used to copy or
move parenthesis demarcated units around the file.

*** Eldoc - Display Elisp information in the mini-buffer.

When coding, it can be useful to have relevant information displayed
in the mini-buffer at the foot of the screen.

#+begin_src emacs-lisp
  ;; ElDoc information displayed in the mini-buffer.
  (add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
  (add-hook 'lisp-interaction-mode-hook 'turn-on-eldoc-mode)
  (add-hook 'ielm-mode-hook 'turn-on-eldoc-mode)
#+end_src
