** Universal Functions and Capabilities.

Settings in this file are considered to be of use pretty much
universally within Emacs. This makes them different from those
functions that are specific to modes such as programming in a
particular language or generating a document in a particular markup
language.

The sort of functions in question are things like adding the closing
bracket whenever the opening bracket is inserted, having word wrapping
switched on by default etc.

*** Making the Default Search Mode 'Regular Expression' Based.

Without the following settings the standard search within Emacs, the
ones accessed using C-s (search forward) and C-r (search backwards)
both use the simple text match. In this case the regular expression
based searching are available using C-M-s and C-M-r. Given how
powerful regular expression searching is, the stanza below makes the
default search type regular expression.

#+begin_src emacs-lisp
  ;; use regular expression searching by default.
  (global-set-key (kbd "C-s") 'isearch-forward-regexp)
  (global-set-key (kbd "C-r") 'isearch-backward-regexp)
  (global-set-key (kbd "C-M-s") 'isearch-forward)
  (global-set-key (kbd "C-M-r") 'isearch-backward)
#+end_src

*** Parenthesis Pairing - Add the closing bracket automatically.

Use electric pair mode will insert the closing entry for a bracket or
similar parenthesis. In this case the definition of bracket includes:

parenthesis - ()
square brackets - []
curly brackets - {}
speech marks - ""
single quotes - ''

The single quotes pairing can be a tricky when writing prose or
Lisp. I should investigate whether this can be switched on or off for
particular modes, or have an easy way to undo the second insertion.

#+begin_src emacs-lisp
  ;; Electric brackets
  (use-package electric
  		    :ensure t
  		    :init
  		    :config (add-hook 'prog-mode-hook 'electric-pair-mode)
  		    :config (add-hook 'LaTeX-mode-hook 'electric-pair-mode)
  		    :config (add-hook 'latex-mode-hook 'electric-pair-mode)
  		    :config (add-hook 'text-mode-hook 'electric-pair-mode)
  		    :config (add-hook 'org-mode-hook 'electric-pair-mode)
  		    :config (add-hook 'pov-mode-hook 'electric-pair-mode))
#+end_src

*** Rainbow Colouring for Parenthesis and Brackets.

The above code is useful for inserting various brackets and delimiters
in pairs. However, as you are editing it would be simple to end up
deleting one of these bracket characters, and suddenly you are in the
situation where you aren't sure whether your brackets are suitably
balanced or not.

The following code provides a way of checking the balance of the
brackets by colouring each opening and closing half of the pair in the
same colour and cycling through the colours as sets of brackets are
recursively added.

#+begin_src emacs-lisp
  ;; Rainbow delimiters for brackets, curly and square braces
  (use-package rainbow-delimiters
    :ensure t
    :init
    :config (add-hook 'prog-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'LaTeX-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'latex-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'text-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'org-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'pov-mode-hook 'rainbow-delimiters-mode))
#+end_src

The Bad Wolf theme cycles through the colours for rainbow parentheses
with strong enough colours that it makes the rainbow bracket function
an effective check on bracket pairing.

*** Bracket/Parentheses Pair Highlighting Function.

The next function in the list that I would normally set up triggers
highlighting of the matching half of a pair of brackets when the
cursor is on the other half. This setting is managed using the
'show-paren-mode variable, setting this to 1. Checking, the value is
already set to the equivalent value of t (for true).

The highlight actually happens as follows:

For a pair of brackets with a space between them, as below, if the
cursor is on the opening item of the pair then the closing item is
highlighted. If the cursor is immediately after the closing item then
both the opening and closing bracket are highlighted in the same
colour.

( )

I'll leave the pair in place above so they can be used for testing and
to familiarise or remind the reader of the behaviour.

*** Spell Checking - On-the-fly Spell Check using UK British Dictionary.

Obviously want to use the British dictionary, what with speaking and
writing proper English...

#+begin_src emacs-lisp
    ;; spellchecking using aspell and configuring to use British.
    (setq ispell-program-name "/usr/bin/aspell")
    (setq ispell-dictionary "british"
          ispell-extra-args '() ;; Tex mode "-t"
          ispell-silently-savep t)

    ;; Configure a personal dictionary.
    (setq ispell-personal-dictionary "~/.backups/ispell-personal-dictionary")

    ;; Flyspell to do the spell checking on the fly.
    (use-package flyspell
      :ensure t
      :init
      :config (add-hook 'text-mode-hook 'flyspell-mode)
      :config (add-hook 'prog-mode-hook 'flyspell-mode)
      :config (add-hook 'LaTeX-mode-hook 'flyspell-mode)
      :config (add-hook 'latex-mode-hook 'flyspell-mode)
      :config (add-hook 'org-mode-hook 'flyspell-mode))

    ;; Flyspell correct helm
    (use-package flyspell-correct
      :after flyspell
      :bind (:map flyspell-mode-map ("C-;" . flyspell-correct-wrapper)))
    (use-package flyspell-correct-helm
      :after flyspell-correct)
#+end_src

The settings above configure the following:

- A location for the personal dictionary file (this is stored in the
  same location as other useful files such as the backups, recentf
  list etc).

- Activate 'flyspell' on the fly spell-checking and enable this for
  the appropriate modes

- Activate 'flyspell-correct' and its 'helm' selection tool as a quick
  way of getting spell-checking done. The helm selection is triggered
  using C-;.

- If the word that is marked as being mis-spelled is one that you wish
  to add to the personal dictionary then use ispell-word, not the
  flyspell-correct wrapper. Trigger the ispell word option using
  M-$. Initially ispell-word will suggest close matches which can be
  selected using the label shown. To add the word to the dictionary
  open the options using C-h, and press 'i' to add to the dictionary.

*** Grammar Checking using Flycheck.

Whenever I enabled the flycheck the Scratch buffer just locked up and
wouldn't respond to the keyboard! So I'm leaving this out for now.

*** Global Line Numbering.

Modern programming languages don't require line numbers, but it can
still be a useful addition to the buffer display to show line
numbers. The line numbers will be shown in the right hand 'gutter' of
the buffer.

#+begin_src emacs-lisp
  ;; Activate line numbering.
  (global-display-line-numbers-mode t)
#+end_src

The numbers can be used as a navigation method:

- M-g g - Then enter the number of the line to move to.

If using the 'folding' function to hide sections of the file then the
line numbering reflects the folding process. 
